#!/bin/sh
#item   ####description                                      ###on off ###
rm -f /tmp/SeTnewtag # empty the return file
dialog --title "SELECTING PACKAGES FOR SERIES IV (InterViews 3.1)" \
       --checklist "Please select the package you wish to install \
from series IV. Recommended packages are selected already, but you \
may select any combination of packages you like. \
Press ENTER when you are \
done." 18 70 8 \
"doc" "DOC word processor - stores in TeX" "on" \
"idraw" "IDRAW graphics editor - stores in .ps" "on" \
"iv_bin" "Other IV apps" "off" \
"iv_docs" "PostScript docs for IV" "off" \
"iv_libs" "Static libs, includes, config files" "off" \
"iv_man" "Man pages for IV programming" "off" \
"iv_misc" "Samples, style sheets for DOC, IDRAW" "on" \
"ivdevbin" "Development binaries" "off" \
2> /tmp/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f /tmp/SeTpkgs
 exit
fi
cat /dev/null > /tmp/SeTnewtag
for PACKAGE in doc idraw iv_bin iv_docs iv_libs iv_man iv_misc ivdevbin ; do
 if fgrep \"$PACKAGE\" /tmp/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> /tmp/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> /tmp/SeTnewtag
 fi
done
rm -f /tmp/SeTpkgs
